CREATE TABLE IF NOT EXISTS users (id BIGINT AUTO_INCREMENT PRIMARY KEY, login VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(20));
CREATE TABLE IF NOT EXISTS orders (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, total_price DECIMAL(18,2));
CREATE TABLE IF NOT EXISTS goods (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255), price DECIMAL(18,2));
CREATE TABLE IF NOT EXISTS orders_goods (order_id BIGINT NOT NULL, good_id BIGINT NOT NULL, count INT NOT NULL);

ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE orders_goods ADD FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE orders_goods ADD FOREIGN KEY (good_id) REFERENCES goods(id);
